name: merge-master-into-develop
on:
  push:
    branches:
      - master
jobs:
  merge-master-into-develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge master -> develop
        uses: devmasx/merge-branch@v1.3.0
        with:
          type: now
          from_branch: master
          target_branch: develop
          github_token: ${{ github.token }}
