name: merge-master-into-develop
on:
  push:
    branches:
      - master
jobs:
  merge-master-into-develop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          ref: develop
      - run: git config user.name github-actions
      - run: git config user.email github-actions@github.com
      - run: git merge origin/master --ff-only
      - run: git push
